version : '3'

services:
  postgres:
    image: 'postgres:latest'
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432



